[opener]
textedit = [
	{ run = '$EDITOR "$@"', orphan = true, for = "unix" },
	{ run = "%EDITOR% %*",  orphan = true, for = "windows" },
]
musicedit = [
	{ run = '$MUSICEDITOR "$@"', orphan = true, for = "unix" },
	{ run = "%MUSICEDITOR% %*",  orphan = true, for = "windows" },
]
imageedit = [
	{ run = '$IMAGEEDITOR "$@"', orphan = true, for = "unix" },
	{ run = "%IMAGEEDITOR% %*",  orphan = true, for = "windows" },
]

[open]
rules = [
    { mime = "text/*", use = "textedit" },
    { name = "*.json", use = "textedit" },

    { mime = "audio/*", use = "musicedit" },
    
    { mime = "image/*", use = "imageedit" },
]
